trc_client:
    resource: "@TRCClientBundle/Resources/config/routing.yml"
    prefix:   /clients

trcddc:
    resource: "@TRCDDCBundle/Resources/config/routing.yml"
    prefix:   /ddc

trc_admin:
    resource: "@TRCAdminBundle/Resources/config/routing.yml"
    prefix:   /

trc_core:
    resource: "@TRCCoreBundle/Resources/config/routing.yml"
    prefix:   /

trc_user:
    resource: "@TRCUserBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
app:
    resource: "@AppBundle/Controller/"
    type:     annotation
