# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CA:     ROLE_AO
        ROLE_RZ:    ROLE_CA
        ROLE_ADMIN:       ROLE_RZ
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
            main:
                    pattern: ^/
                    anonymous: true
                    provider: fos_userbundle
                    form_login:
                         login_path: fos_user_security_login
                         check_path: fos_user_security_check
                         #success_handler: farm_homepage
                    logout:
                        path: fos_user_security_logout
                        target: fos_user_security_login
                    #    success_handler: crm_user_security.authentication.logout_success_handler
                    #remember_me:
                    #    key: 2a622b528fcef0753a01263dbffc87627c967c54
            dev:
               pattern:  ^/(_(profiler|wdt)|css|images|js)/
               security: false
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/, role: ROLE_USER }
        # require ROLE_ADMIN for /admin*
        
