<?php

namespace Proxies\__CG__\TRC\CoreBundle\Entity\DDC;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EDDC extends \TRC\CoreBundle\Entity\DDC\EDDC implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'id', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'dateajout', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'etat', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'fonction', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'pddc', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'active', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'verdict', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'decision', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'commentaire'];
        }

        return ['__isInitialized__', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'id', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'dateajout', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'etat', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'fonction', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'pddc', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'active', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'verdict', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'decision', '' . "\0" . 'TRC\\CoreBundle\\Entity\\DDC\\EDDC' . "\0" . 'commentaire'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EDDC $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateajout($dateajout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateajout', [$dateajout]);

        return parent::setDateajout($dateajout);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateajout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateajout', []);

        return parent::getDateajout();
    }

    /**
     * {@inheritDoc}
     */
    public function setEtat(\TRC\CoreBundle\Entity\DDC\Etat $etat)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEtat', [$etat]);

        return parent::setEtat($etat);
    }

    /**
     * {@inheritDoc}
     */
    public function getEtat()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEtat', []);

        return parent::getEtat();
    }

    /**
     * {@inheritDoc}
     */
    public function setPddc(\TRC\CoreBundle\Entity\DDC\PDDC $pddc)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPddc', [$pddc]);

        return parent::setPddc($pddc);
    }

    /**
     * {@inheritDoc}
     */
    public function getPddc()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPddc', []);

        return parent::getPddc();
    }

    /**
     * {@inheritDoc}
     */
    public function setActeur(\TRC\CoreBundle\Entity\Acteur $acteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActeur', [$acteur]);

        return parent::setActeur($acteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getActeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActeur', []);

        return parent::getActeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setFonction(\TRC\CoreBundle\Entity\Fonction $fonction = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFonction', [$fonction]);

        return parent::setFonction($fonction);
    }

    /**
     * {@inheritDoc}
     */
    public function getFonction()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFonction', []);

        return parent::getFonction();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive($active)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getActive()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setVerdict($verdict)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setVerdict', [$verdict]);

        return parent::setVerdict($verdict);
    }

    /**
     * {@inheritDoc}
     */
    public function getVerdict()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getVerdict', []);

        return parent::getVerdict();
    }

    /**
     * {@inheritDoc}
     */
    public function setDecision(\TRC\CoreBundle\Entity\DDC\Decision $decision = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDecision', [$decision]);

        return parent::setDecision($decision);
    }

    /**
     * {@inheritDoc}
     */
    public function getDecision()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDecision', []);

        return parent::getDecision();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentaire($commentaire)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentaire', [$commentaire]);

        return parent::setCommentaire($commentaire);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentaire()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentaire', []);

        return parent::getCommentaire();
    }

}
