<?php

namespace TRC\CoreBundle\Repository\Client;

/**
 * CECRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CECRepository extends \Doctrine\ORM\EntityRepository
{
}
