<?php

namespace TRC\CoreBundle\Repository\Client;

/**
 * LDPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LDPRepository extends \Doctrine\ORM\EntityRepository
{
}
