<?php

namespace TRC\CoreBundle\Repository\Client;

/**
 * NatureCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NatureCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
