<?php

namespace Proxies\__CG__\TRC\CoreBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Notification extends \TRC\CoreBundle\Entity\Notification implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = [];



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'id', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'titre', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'contenu', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'datenoti', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'lu', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'alerte', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'acteur', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'entite'];
        }

        return ['__isInitialized__', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'id', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'titre', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'contenu', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'datenoti', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'lu', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'alerte', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'acteur', '' . "\0" . 'TRC\\CoreBundle\\Entity\\Notification' . "\0" . 'entite'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Notification $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setContenu($contenu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setContenu', [$contenu]);

        return parent::setContenu($contenu);
    }

    /**
     * {@inheritDoc}
     */
    public function getContenu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getContenu', []);

        return parent::getContenu();
    }

    /**
     * {@inheritDoc}
     */
    public function setDatenoti($datenoti)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDatenoti', [$datenoti]);

        return parent::setDatenoti($datenoti);
    }

    /**
     * {@inheritDoc}
     */
    public function getDatenoti()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDatenoti', []);

        return parent::getDatenoti();
    }

    /**
     * {@inheritDoc}
     */
    public function setLu($lu)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLu', [$lu]);

        return parent::setLu($lu);
    }

    /**
     * {@inheritDoc}
     */
    public function getLu()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLu', []);

        return parent::getLu();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitre($titre)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitre', [$titre]);

        return parent::setTitre($titre);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitre()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitre', []);

        return parent::getTitre();
    }

    /**
     * {@inheritDoc}
     */
    public function setActeur(\TRC\CoreBundle\Entity\Acteur $acteur = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActeur', [$acteur]);

        return parent::setActeur($acteur);
    }

    /**
     * {@inheritDoc}
     */
    public function getActeur()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActeur', []);

        return parent::getActeur();
    }

    /**
     * {@inheritDoc}
     */
    public function setEntite(\TRC\CoreBundle\Entity\Entite $entite = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEntite', [$entite]);

        return parent::setEntite($entite);
    }

    /**
     * {@inheritDoc}
     */
    public function getEntite()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEntite', []);

        return parent::getEntite();
    }

    /**
     * {@inheritDoc}
     */
    public function setAlerte($alerte)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAlerte', [$alerte]);

        return parent::setAlerte($alerte);
    }

    /**
     * {@inheritDoc}
     */
    public function getAlerte()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAlerte', []);

        return parent::getAlerte();
    }

}
