trc_client_homepage:
    path:     /
    defaults: { _controller: TRCClientBundle:Default:index }
trc_client_recherche:
    path:     /recherche
    defaults: { _controller: TRCClientBundle:Default:recherche }

trc_client_consulter:
    path:     /{radical}
    defaults: { _controller: TRCClientBundle:Default:consulter }
trc_client_ajouter_comptes:
    path:     /{radical}/comptes
    defaults: { _controller: TRCClientBundle:Default:ajouterCompte }
trc_client_modifier_comptes:
    path:     /{radical}/comptes/{id}
    defaults: { _controller: TRCClientBundle:Default:ajouterCompte }
trc_client_voir_rubrique:
    path:     /{radical}/voir/{rubrique}
    defaults: { _controller: TRCClientBundle:Default:voirrubrique }

trc_client_identite:
    path:     /{radical}/identite
    defaults: { _controller: TRCClientBundle:MAJ:identite }

trc_client_coordonnee:
    path:     /{radical}/coordonnées
    defaults: { _controller: TRCClientBundle:MAJ:coordonnees }
trc_client_employeur:
    path:     /{radical}/employeur
    defaults: { _controller: TRCClientBundle:MAJ:employeur }

trc_client_profession:
    path:     /{radical}/profession
    defaults: { _controller: TRCClientBundle:MAJ:profession }
trc_client_revenu:
    path:     /{radical}/revenu
    defaults: { _controller: TRCClientBundle:MAJ:revenu }
trc_client_logement:
    path:     /{radical}/logement
    defaults: { _controller: TRCClientBundle:MAJ:logement }

trc_client_pac:
    path:     /{radical}/pac
    defaults: { _controller: TRCClientBundle:MAJ:pac }