<?php

namespace TRC\CoreBundle\Repository;

/**
 * BOCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BOCRepository extends \Doctrine\ORM\EntityRepository
{
}
