<?php

namespace TRC\CoreBundle\Repository;

/**
 * CICRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CICRepository extends \Doctrine\ORM\EntityRepository
{
}
