<?php

namespace TRC\CoreBundle\Repository;

/**
 * DDPRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DDPRepository extends \Doctrine\ORM\EntityRepository
{
}
