<?php

namespace TRC\CoreBundle\Repository;

/**
 * TDCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TDCRepository extends \Doctrine\ORM\EntityRepository
{
}
