<?php

namespace TRC\CoreBundle\Repository;

/**
 * TypeJournalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypeJournalRepository extends \Doctrine\ORM\EntityRepository
{
}
