services:
#    trc_core.example:
#        class: TRC\CoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    trc_core.connexion:
        class: TRC\CoreBundle\Connected\Connected
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
        tags:
           - { name: kernel.event_listener, event: security.authentication.success,method: onKernelLogOk }

  #  trc_core.interactivelogin:
  #      class: TRC\CoreBundle\Interactivelogin\Interactivelogin
  #      arguments: []
  #      calls:
  #          - [setEntityManager, ["@doctrine.orm.entity_manager"]]
  #      tags:
  #         - { name: kernel.event_listener, event: security.interactive_login,method: onKernelLogOk }

    trc_core.authenticationfail:
        class: TRC\CoreBundle\Authentificationfail\Authentificationfail
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]
        tags:
           - { name: kernel.event_listener, event: security.authentication.failure,method: onKernelLogOk }

#*********** LES SYSTEMES ******************
    trc_core.sp:
        class: TRC\CoreBundle\Systemes\SP\Pagination
        arguments: []
        calls:
            - [setEntityManager, ["@doctrine.orm.entity_manager"]]