<?php

namespace TRC\CoreBundle\Repository\DDC;

/**
 * CDCDRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CDCDRepository extends \Doctrine\ORM\EntityRepository
{
}
