<?php

namespace TRC\CoreBundle\Repository\DDC;

/**
 * DOCTDCRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DOCTDCRepository extends \Doctrine\ORM\EntityRepository
{
}
