trc_admin_homepage:
    path:     /admin
    defaults: { _controller: TRCAdminBundle:Default:index }

trc_admin_utilisateurs:
    path:     /admin/utilisateurs
    defaults: { _controller: TRCAdminBundle:Utilisateurs:utilisateurs }

trc_admin_utilisateurs_ajouter:
    path:     /admin/utilisateurs/ajouter
    defaults: { _controller: TRCAdminBundle:Utilisateurs:utilisateursAjouter }
trc_admin_utilisateurs_voir:
    path:     /admin/utilisateur/{matricule}
    defaults: { _controller: TRCAdminBundle:Utilisateurs:utilisateursVoir }

trc_admin_utilisateurs_affectation_a_une_entite:
    path:     /admin/utilisateur/{matricule}/{entite}/affectation
    defaults: { _controller: TRCAdminBundle:Utilisateurs:affectation }
    requirements:
          entite: Agence|CIC|BOC|Zone

trc_admin_affectation_de_profil_a_une_fonction:
    path:     /admin/utilisateur/{matricule}/{entite}/affectation/{idfonction}
    defaults: { _controller: TRCAdminBundle:Utilisateurs:affectation }
    requirements:
          entite: Agence|CIC|BOC|Zone

trc_admin_entites:
    path:     /admin/entites
    defaults: { _controller: TRCAdminBundle:Entites:entites }

trc_admin_entites_ajouter:
    path:     /admin/entites/ajouter/{entite}
    defaults: { _controller: TRCAdminBundle:Entites:entitesAjout }
    requirements:
          entite: Agence|CIC|BOC|Zone

trc_admin_entites_modifier:
    path:     /admin/entites/modifier/{entite}/{matricule}
    defaults: { _controller: TRCAdminBundle:Entites:entitesAjout }
    requirements:
          entite: Agence|CIC|BOC|Zone

trc_admin_entites_voir_une:
    path:     /admin/entites/{entite}/{code}
    defaults: { _controller: TRCAdminBundle:Entites:entitesVoirUne }
    requirements:
          entite: Agence|CIC|BOC|Zone

trc_admin_entites_par_categorie:
    path:     /admin/entites/{entite}
    defaults: { _controller: TRCAdminBundle:Entites:entitesParCategorie }
    requirements:
          entite: Agence|CIC|BOC|Zone



trc_admin_profils:
    path:     /admin/profils
    defaults: { _controller: TRCAdminBundle:Profils:ajouter }

trc_admin_profils_voir:
    path:     /admin/profils/{matricule}
    defaults: { _controller: TRCAdminBundle:Profils:voir }

trc_admin_systemes:
    path:     /admin/systemes
    defaults: { _controller: TRCAdminBundle:Systemes:systemes }

trc_admin_tdc:
    path:     /admin/crédits
    defaults: { _controller: TRCAdminBundle:Credits:credits }

trc_admin_tdc_voir:
    path:     /admin/crédits/{code}
    defaults: { _controller: TRCAdminBundle:Credits:creditsvoir }
